name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Repository letöltése
      - name: Checkout Repository
        uses: actions/checkout@v2

      # .NET környezet beállítása
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # Projekt buildelése WebSharper-rel (.NET)
      - name: Build Project with WebSharper
        run: dotnet build

      # Scripts mappa másolása (WebSharper JavaScript fájlok)
      - name: Copy WebíSharper scripts to dist/
        run: cp -r bin/Debug/Scripts/WebSharper dist/Scripts/WebSharper

      # További HTML fájlok másolása
      - name: Copy additional HTML files to dist/
        run: cp bin/html/*.html dist/

      # .nojekyll fájl hozzáadása
      - name: Add .nojekyll file
        run: echo > dist/.nojekyll

      # Telepítés GitHub Pages-re 
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
      
      
      # 9. GitHub CLI API hívás és issue létrehozása
      - name: Create Issue with GitHub CLI
        run: |
          # API hívás az aktuális nyitott issue-k számának lekéréséhez
          numOpenIssues=$(gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            query($name: String!, $owner: String!) {
              repository(owner: $owner, name: $name) {
                issues(states:OPEN) {
                  totalCount
                }
              }
            }' --jq '.data.repository.issues.totalCount')

          echo "Open issues count is $numOpenIssues"

          # Issue létrehozása az aktuális nyitott issue-k számával
          gh issue create --title "Issue Report" --body "There are currently $numOpenIssues open issues in this repository." --repo $OWNER/$REPO

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
